### ISSUE TITLE
'set nocount on' prevents versionnumber from being updated.

### ISSUE THREAD

**Issue by benpriebe** [Rophuine/NSchemer#5]
If a script has 'set nocount on' and doesn't revert it the sql to update the nschemer_version table with an updated version number returns false and the whole transition fails.

It might be worth programming defensively against this, by ensuring nocount is off.

![image](https://cloud.githubusercontent.com/assets/1300551/11771267/9cef55fe-a259-11e5-917d-8dc82601b4fa.png)

**Comment by Rophuine** [comment]
I've had a chat with one of the DbUp guys, and he said they just haven't been checking counts - seems like a good approach. I'm hesitant to do updates until I get a decent system test going - I was relying on PEL's setup while I was there.

Let me know if you're keen to test updates, otherwise I'll try to get something going soon.

**Comment by benpriebe** [comment]
Happy to test any changes, also happy to wait.

**Comment by Rophuine** [comment]
Version 0.1.5882.37363 should fix this, as well as including Gerrod's timeout code.
